name: practice preview

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v4
        with:
          html_file: 'index.html'
          job_summary: true
      - name: Log HTML Preview URL
        run: echo "${{ steps.html_preview.outputs.url }}"
